<?php

namespace Application\TwitterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository {
	
	public function findAllOrderedByDateAdded() {
		return $this -> getEntityManager() -> createQuery('SELECT p FROM ApplicationTwitterBundle:Tweet p ORDER BY p.date_added DESC') -> setMaxResults(5)-> getResult();
		 
		
	}

}
