parameters:
#    application_menu.example.class: Application\MenuBundle\Example

services:
#    application_menu.example:
#        class: %application_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
