<?php

namespace Application\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository {

	public function findAllOrderedByOrder() {
		return $this->getEntityManager()->createQuery('SELECT p FROM ApplicationMenuBundle:Menu p ORDER BY p.orderby ASC') -> getResult();
	}

}
